stages:
  - buildDev
  - deployDev

image: gitlab/dind
services:
  - docker:dind

deployDev:
  before_script:
    - export PATH=$PATH:/home/gitlab-runner/.nvm/versions/node/v14.17.6/bin
  stage: deployDev
  tags:
    - passon-api-demo-server
  only:
      - deployDev
  script:
    - source ~/.nvmrc
    - yarn install
    - cp "${DEV_ENV}" .env
    - cp "${DB_CONFIG}" ./database/config/config.js
    - pm2 delete  ecosystem.config.js
    - pm2 start  ecosystem.config.js   
